create table PURCHASE_BOARD (
	PB_NO NUMBER, 		--글번호
	PB_WRTIER VARCHAR2(30),	--작성자
	PB_TITLE  VARCHAR2(30),	--제목
	PB_CONTENT VARCHAR2(4000),	--내용
	PB_FILE VARCHAR2(50),	--파일
	PB_READCOUNT NUMBER,--조회수
	PB_DATE DATE,		--날짜
	PRIMARY KEY(PB_NO)
);

SELECT * FROM PURCHASE_BOARD;