
DROP TABLE CATEGORY;

CREATE TABLE CATEGORY(
	CATEGORY_ID		NUMBER			PRIMARY KEY,
	CATEGORY_NAME	VARCHAR2(100)	NOT NULL
)

INSERT INTO CATEGORY VALUES(1, '의류/잡화');
INSERT INTO CATEGORY VALUES(2, '뷰티');
INSERT INTO CATEGORY VALUES(3, '식품/생활/유아동');
INSERT INTO CATEGORY VALUES(4, '가구');
INSERT INTO CATEGORY VALUES(5, '가전/디지털');
INSERT INTO CATEGORY VALUES(6, '도서/쿠폰');
INSERT INTO CATEGORY VALUES(7, '기타');

SELECT * FROM CATEGORY;
