DROP TABLE PURCHASE_HISTORY;

CREATE TABLE PURCHASE_HISTORY(
	PH_NO			NUMBER			PRIMARY KEY,		-- 거래번호
	PH_BOARD_NO		NUMBER			REFERENCES SELL_BOARD(SB_NO), 	-- 판매게시글 번호
	PH_MEMBER		VARCHAR2(100)	REFERENCES MEMBER(ID),	-- 사용자
	PH_OPPONENT		VARCHAR2(50)	REFERENCES MEMBER(ID),	-- 거래상대
	PH_DATE			DATE			NOT NULL,		-- 거래완료일시 (INSERT시 SYSDATE)
	PH_STATE		NUMBER							-- 거래중(0), 거래완료(1)
);