CREATE TABLE PURCHASE_BOARD(
	PB_NO NUMBER,
	PB_WRITER VARCHAR2(30),
	PB_PASSWORD VARCHAR2(30),
	PB_TITLE VARCHAR2(300),
	PB_CONTENT(4000),
	PB_PICTURE(50),
	PB_REF NUMBER,
	PB_LEV NUMBER,
	PB_SEQ NUMBER
	
)