CREATE TABLE SELL_BOARD(
	SB_NO		NUMBER,
	SB_WRITER	VARCHAR2(15),
	SB_PDATE	DATE,
	SB_TITLE	VARCHAR2(30),
	SB_CONTENT	VARCHAR2(200),
	SB_PRICE	NUMBER,
	SB_DATE		DATE,
	SB_READCOUNT	NUMBER,
	PRIMARY KEY(SB_NO)
);

ALTER TABLE SELL_BOARD
RENAME COLUMN SB_BDATE TO SB_PDATE;

alter table SELL_BOARD ADD (SB_MDATE DATE DEFAULT SYSDATE);

DROP TABLE SELL_BOARD;

SELECT * FROM SELL_BOARD;

CREATE TABLE REPORT_BOARD(
	RB_NO		NUMBER,
	RB_WRITER	VARCHAR2(15),
	RB_TITLE	VARCHAR2(30),
	RB_CONTENT	VARCHAR2(200),
	PRIMARY KEY(RB_NO)
);


select * from (select rownum rnum, SB_NO, SB_WRITER, SB_TITLE, 
	SB_READCOUNT, SB_DATE from 
	(select * from SELL_BOARD where SB_TITLE LIKE '%123%' 
	order by SB_NO desc)) where rnum>=1 and rnum<=5;
	
select rownum rnum, SB_NO, SB_WRITER, SB_TITLE, SB_READCOUNT, SB_DATE 
	from (select * from SELL_BOARD where SB_TITLE LIKE '%123%' order by SB_NO desc);
	
select * from (select rownum rnum, SB_NO, SB_WRITER, SB_TITLE, SB_READCOUNT, SB_DATE 
	from (select * from SELL_BOARD where SB_TITLE LIKE '%123%' order by SB_NO desc)) where rnum>=1 and rnum<=5;