DROP TABLE SELL_HISTORY;

CREATE TABLE SELL_HISTORY(
	SH_NO			NUMBER			PRIMARY KEY,		-- 거래번호
	SH_BOARD_NO		NUMBER			FOREIGN KEY(SH_BOARD_NO) REFERENCES SELL_BOARD(SB_NO), 	-- 판매게시글 번호
	SH_MEMBER		VARCHAR2(15)	FOREIGN KEY(SH_MEMEBER) REFERENCES MEMBER(ID),	-- 사용자
	SH_DATE			DATE			NOT NULL		-- 거래완료일시 (INSERT시 SYSDATE)
	SH_STATE		NUMBER							-- 거래중(0), 거래완료(1)
);