$(document).ready(function(){
	$('#list_detail').click(function(){
		location.href='BoardDetail.sell';
	});
	$('#list_write').click(function(){
		location.href='BoardWrite.sell';
	});
	$('#view_modify').click(function(){
		location.href='BoardModifyView.sell';
	});
	$('#view_delete').click(function(){
		location.href='BoardDelete.sell';
	});
	$('#view_list').click(function(){
		location.href='BoardList.sell';
	});
});